// Stock productos \\

let stockTotal = [
  {
    id: 1,
    cantidad: 1,
    nombre: "kimonoHombre1",
    tipo: "Kimono Gold",
    genero: "hombre",
    precio: 3000,
    talle: "1",
    img: "assets/kimono2.png",
    info: "lorem sgfdzdghnxfjgxfhjxghjkcxgjhkm",
  },
  {
    id: 2,
    cantidad: 1,
    nombre: "pantalonHombre",
    tipo: "Pantalón Black",
    genero: "hombre",
    precio: 2000,
    talle: "1",
    img: "assets/pantalon negro.jpg",
  },
  {
    id: 3,
    cantidad: 1,
    nombre: "kimonoHombre2",
    tipo: "Kimono Black",
    genero: "hombre",
    precio: 3000,
    talle: "1",
    img: "assets/kimonoblack.jpg",
  },
  {
    id: 4,
    cantidad: 1,
    nombre: "kimonoMujer1",
    tipo: "Kimono Night",
    genero: "mujer",
    precio: 3000,
    talle: "1",
    img: "assets/kimonoMujer.jpeg",
  },
  {
    id: 5,
    cantidad: 1,
    nombre: "pantalonMujer1",
    tipo: "Pantalón Spring",
    genero: "mujer",
    precio: 2000,
    talle: "1",
    img: "assets/pantalonMujer1.jpg",
  },
  {
    id: 6,
    cantidad: 1,
    nombre: "kimonoMujer2",
    tipo: "Kimono Spring",
    genero: "mujer",
    precio: 3000,
    talle: "1",
    img: "assets/kimonoSpring.jpg",
  },
];
